info:
  contact: {}
paths:
  /healthz:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Healthz
      tags:
      - healthz
swagger: "2.0"
